# Generated by Django 3.2.4 on 2021-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0003_auto_20210622_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50)),
                ('st_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='oil',
            name='standard',
            field=models.ManyToManyField(related_name='oils', to='platinum.Standard'),
        ),
    ]
