# Generated by Django 3.2.4 on 2021-06-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0004_auto_20210622_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='oil',
            name='img',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='price',
        ),
    ]
