# Generated by Django 3.2.4 on 2021-06-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0005_auto_20210623_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='oils/')),
                ('oil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platinum.oil')),
            ],
            options={
                'ordering': ['oil'],
            },
        ),
    ]
