# Generated by Django 3.2.4 on 2021-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0008_auto_20210626_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('d', 'Done'), ('w', 'In work')], default='w', max_length=1),
        ),
    ]
