# Generated by Django 3.2.4 on 2021-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0009_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
