# Generated by Django 3.2.4 on 2021-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0010_alter_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
