# Generated by Django 3.2.4 on 2021-06-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0014_alter_customer_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='oil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platinum.oilinstance'),
        ),
    ]
