# Generated by Django 3.2.4 on 2021-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0015_alter_cart_oil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
