# Generated by Django 3.2.4 on 2021-06-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0017_alter_customer_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cart',
            new_name='order',
        ),
    ]
