# Generated by Django 3.2.4 on 2021-06-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0018_rename_cart_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platinum.oilinstance'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
