# Generated by Django 3.2.4 on 2021-06-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0019_auto_20210626_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='oil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platinum.oilinstance'),
        ),
    ]
