# Generated by Django 3.2.4 on 2021-06-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platinum', '0020_alter_cart_oil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
